### ISSUE TITLE
How to implement playlist controls like loop, shuffle, and repeat?

### ISSUE THREAD

**Issue by DouSN** [gafsel/flutter_plugin_playlist#17]
Does this library come with an API to control how to music plays? I've read through the docs and since I wasn't able to find it, I would appreciate some suggestions as to how to implement this behavior.

**Comment by gafsel** [comment]
Hello @pingxiaodou 

The loop feature already exists. You can enable and disable it by calling setLoop(bool) at RmxAudioPlayer.

The shuffle and the repeat features are yet to be implemented.

**Comment by DouSN** [comment]
@gafsel Thanks for you reply.If I want to implement this feature in dart,How can I konw when the audio finishes playing(It does not fire when interrupt the audio with pause or stop)？

**Comment by gafsel** [comment]
I wouldn't recommend implementing it on Dart as it would be against the plugin proposal (audio playlist management on native instead of in Dart) but if you really need this feature and can't wait for the next release and/or can't contribute with the native implementation yourself, here a suggestion of the solution in Dart:

**repeat feature**: 

For repeating a single song, you can simply add only one song to the playlist and enable loop. When the song ends it will start playing again. 

_Downs:_ The audio navigation controller on Android and iOS won't be enabled as the playlist actually has only one song and theoretically would need navigation.

**shuffle feature:** 

This one is easier. You can simply shuffle the playlist before adding it to the plugin.

_Downs:_ You will have to maintain the original playlist in Dart memory or even on local storage so the app can identify the original index of the current playing track.

At last, for listening for any kind of events you can call `on(String eventName, AudioPlayerEventHandler callback)`. The callback will receive an object containing the data from the current current player status including the current track. For more details on that, take a look at our example where the app changes it interface as the player status changes.

Hope this will help you. Keep subscribed to the repository so you be notified when the release with these features is avaiable.
